GSharker/G-Shark

VerbNurbsSharp/Core/Data.cs, VerbNurbsSharp/Evaluation/Check.cs
=> Check completed 

VerbNurbsSharp/Evaluation/Divide.cs, VerbNurbsSharp/Evaluation/Eval.cs, VerbNurbsSharp/Evaluation/Modify.cs
=> create new branch

README.md
Sorry, next time better if I use a separate branch.
=> README.md updated from stackedit.io

GeometrySharp.Test.XUnit/Core/LinearAlgebraTest.cs, GeometrySharp.Test.XUnit/Core/MathTest.cs, GeometrySharp.Test.XUnit/Core/MatrixTest.cs, GeometrySharp.Test.XUnit/Core/SetsTest.cs, GeometrySharp.Test.XUnit/Core/TrigTest.cs, GeometrySharp.Test.XUnit/Evaluation/DivideTest.cs, GeometrySharp.Test.XUnit/Evaluation/EvalTest.cs, GeometrySharp.Test.XUnit/Evaluation/ModifyTest.cs, GeometrySharp.Test.XUnit/Geometry/LineTest.cs, GeometrySharp.Test.XUnit/Geometry/NurbsCurveTest.cs
=> Refactored the name of the tests.

GeometrySharp.Test.XUnit/Geometry/BoundingBoxTests.cs, GeometrySharp/Geometry/BoundingBox.cs
Added a constructor to BoundingBox.
=> Fixed BoundingBox test problem.

src/GShark.Test.XUnit/Core/LinearAlgebraTests.cs, src/GShark.Test.XUnit/Core/TransformTests.cs, src/GShark.Test.XUnit/Core/TrigonometryTests.cs, src/GShark/Core/LinearAlgebra.cs
=> Update core tests.

src/GShark.Test.XUnit/Operation/TessellationTests.cs
=> Tessellation tests

src/GShark/Geometry/Plane.cs
=> Clean up plane transform.

src/GShark.Test.XUnit/Geometry/ArcTests.cs, src/GShark.Test.XUnit/Geometry/CircleTests.cs, src/GShark.Test.XUnit/Geometry/LineTests.cs, src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs, src/GShark.Test.XUnit/Operation/FittingTests.cs, src/GShark.Test.XUnit/Operation/ModifyTests.cs, src/GShark.Test.XUnit/Operation/TessellationTests.cs, src/GShark/Core/BoundingBoxTree/BoundingBoxOperations.cs, src/GShark/Core/BoundingBoxTree/LazyCurveBBT.cs, src/GShark/Geometry/Arc.cs, src/GShark/Geometry/Circle.cs, src/GShark/Geometry/Interfaces/ICurve.cs, src/GShark/Geometry/Line.cs, src/GShark/Geometry/NurbsCurve.cs, src/GShark/Geometry/NurbsSurface.cs, src/GShark/Geometry/Polyline.cs, src/GShark/Operation/Analyze.cs, src/GShark/Operation/Divide.cs, src/GShark/Operation/Evaluation.cs, src/GShark/Operation/Modify.cs, src/GShark/Operation/Tessellation.cs
Renamed ControlPoints and HomogenizedPoints.
#172
=> Renamed ControlPoints and HomogenizedPoints.

src/GShark.Test.XUnit/Operation/IntersectionTests.cs, src/GShark/Core/GeoSharkMath.cs, src/GShark/Geometry/NurbsCurve.cs, src/GShark/Geometry/Point3.cs, src/GShark/Geometry/Point4.cs, src/GShark/Geometry/Vector.cs, src/GShark/Geometry/Vector3.cs, src/GShark/Operation/IntersectionRefiner.cs
Removed old toDos.
Added truncate method.
Updated ToString for Point3, Point4, Vector3, Vector.
Added removed duplicate points into NurbCurve BBox.
=> Removed old toDos.

src/GShark/GShark.csproj
=> fixed path for the gshark logo.

src/GShark.Test.XUnit/Core/KnotVectorTests.cs, src/GShark/Core/KnotVector.cs
Fixes: Knot multiplicity methods
Fixes #232
=> Fix knot multiplicity.

src/GShark/Core/GeoSharkMath.cs, src/GShark/Core/Interval.cs, src/GShark/Core/KnotVector.cs, src/GShark/Core/Trigonometry.cs, src/GShark/Geometry/Arc.cs, src/GShark/Geometry/BoundingBox.cs, src/GShark/Geometry/Circle.cs, src/GShark/Geometry/ConvexHull.cs, src/GShark/Geometry/NurbsCurve.cs, src/GShark/Operation/Analyze.cs
=> addressed issue #236

src/GShark/ExtendedMethods/Curve.cs
=> Remove ToDos

src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs, src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs, src/GShark/Geometry/NurbsCurve.cs, src/GShark/Geometry/NurbsSurface.cs
Refactor some tests.
This PR fixes the bug ``isClosed`` method.
This PR closes #229
=> Fixed problem for isClosed.

src/GShark/Core/BoundingBoxTree/LazyCurveBBT.cs, src/GShark/Geometry/Line.cs, src/GShark/Geometry/NurbsCurve.cs, src/GShark/Geometry/Vector.cs
Addresses compiler warnings.
Closes #269
=> Refactor to address warnings.

.github/workflows/build-docs.yml, .github/workflows/create-release.yml, .github/workflows/publish-on-release.yml
Improves workflow performance by speeding up setup of .NET and running on ubuntu.
=> Update workflows to run on ubuntu, speed up .NET setup.

src/GShark.Test.XUnit/Core/TrigonometryTests.cs, src/GShark/Core/Trigonometry.cs, src/GShark/Geometry/Circle.cs, src/GShark/Operation/Analyze.cs
Renames method. Moves method to Analyze.
Closes #308
=> Rename method. Move method.

src/GShark.Test.XUnit/Operation/IntersectionTests.cs, src/GShark/GShark.csproj, src/GShark/Geometry/Circle.cs, src/GShark/Geometry/Polyline.cs, src/GShark/Interfaces/IBoundingBoxTree.cs, src/GShark/Intersection/BoundingBoxTree/BoundingBoxOperations.cs, src/GShark/Intersection/BoundingBoxTree/LazyCurveBBT.cs, src/GShark/Intersection/CurvePlaneIntersectionResult.cs, src/GShark/Intersection/CurvesIntersectionResult.cs, src/GShark/Intersection/Intersect.cs, src/GShark/Intersection/IntersectionRefiner.cs
- Refactors Intersection namespaces.
- Adds placeholder folders.
This PR closes #310
=> Refactors Intersection namespaces. Adds placeholder folders.

src/GShark/GShark.csproj, src/GShark/Geometry/Polyline.cs, src/GShark/Operation/Modify.cs
This PR refactor the join method.
=> Refactor join method.

src/GShark.Test.XUnit/Fitting/CurveTests.cs, src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs, src/GShark/Core/CurveHelpers.cs, src/GShark/Fitting/Curve.cs, src/GShark/Geometry/NurbsCurve.cs, src/GShark/Geometry/NurbsSurface.cs
Moved a parametrization method into CurveHelpers.
This PR starts the transition to the new structure and namespaces.
This PR closes #340
=> Extracted ``Fitting``

src/GShark.Test.XUnit/Evaluate/CurveTests.cs, src/GShark.Test.XUnit/Evaluate/SurfaceTests.cs, src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs, src/GShark/Analyze/Curve.cs, src/GShark/Analyze/Surface.cs, src/GShark/Core/Extrema.cs, src/GShark/Evaluate/Curve.cs, src/GShark/Evaluate/Surface.cs, src/GShark/Fitting/Curve.cs, src/GShark/Geometry/NurbsBase.cs, src/GShark/Geometry/NurbsSurface.cs, src/GShark/Geometry/Plane.cs, src/GShark/Geometry/Polygon.cs, src/GShark/Modify/Curve.cs, src/GShark/Optimization/CurvePlaneIntersectionObjectives.cs, src/GShark/Optimization/CurvesIntersectionObjectives.cs, src/GShark/Sampling/Curve.cs
This PR creates the ``Evaluate`` namespace and refactor the ``Evaluate`` class.
This PR closes #342
=> Created ``Evaluate`` namespace.

src/GShark.Test.XUnit/Data/NurbsSurfaceCollection.cs, src/GShark.Test.XUnit/Geometry/LineTests.cs, src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs, src/GShark.Test.XUnit/Sampling/CurveTests.cs, src/GShark/Geometry/Line.cs, src/GShark/Geometry/NurbsBase.cs, src/GShark/Geometry/NurbsCurve.cs, src/GShark/Geometry/PolyCurve.cs, src/GShark/Intersection/Intersect.cs
This PR replace the inheritance ``ICurve`` with ``NurbsBase`` for ``Line``.
This PR closes #353
=> Line inheritance NurbsBase.

src/GShark/Analyze/Curve.cs
=> infinite curvature bug fix

src/GShark/Geometry/Point3.cs
=> converted point3 from struct to class

src/GShark/GShark.csproj
Modifies nuget package description and summary.
=> Update package description.

src/GShark/GShark.csproj
This PR generate xml documentation api file on build.
The GShark.xml file generated in bin folder will included into nuget package with benefit for nuget package users that can view members documentation from their IDE intellisense.
=> Generate  GShark.xml api documentation on build

.github/workflows/release-drafter.yml
Simple PR to check if the process works correctly.
=> Update release draft

src/GShark.Test.XUnit/Geometry/Point3Tests.cs, src/GShark/Geometry/Point3.cs
=> Add method point is on line

src/GShark.Test.XUnit/Geometry/Point3Tests.cs, src/GShark/Geometry/Point3.cs
Add function project a point to plane
=> add project point to plane

src/GShark.Test.XUnit/Geometry/Point3Tests.cs, src/GShark/Geometry/Point3.cs
=> Add Get Centroid method

src/GShark.Test.XUnit/Geometry/Vector3Tests.cs, src/GShark.Test.XUnit/Geometry/VectorTests.cs, src/GShark/Geometry/Vector3.cs
=> Add TripleProduct Method
